name: Android CI

on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Android Build
        uses: ./.github/actions/setup-android-build

      - name: Build
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3.1.3
        with:
          path: app/build/outputs/apk/debug/*.apk
