name: Android CI

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v4

      - name: Setup Android Build
        uses: ./.github/actions/setup-android-build

      - name: Build
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/debug/*.apk

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v4

      - name: Setup Android Build
        uses: ./.github/actions/setup-android-build

      - name: Build
        run: ./gradlew lint --stacktrace
